spring.application.name=BackendApp

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/CRM}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Srisat1$}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret
jwt.secret=${JWT_SECRET:t5JX59LxvclJZbHFhfPfNkdC13N3Oyl+JAHeYvztHMg=}

# Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME:default}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:ZL7TWQAzSr4uN1azgZ4QEO2QRgijqv2j}

# Application URLs
app.verification-url=${VERIFICATION_URL:http://localhost:8080/auth/verify-email}
app.password-reset-url=${PASSWORD_RESET_URL:http://localhost:8080/auth/reset-password}

# Server Configuration
server.port=${PORT:8080}

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:srihaas24@gmail.com}
spring.mail.password=${MAIL_PASSWORD:gdnzabxrsangldem}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#spring.application.name=BackendApp
#spring.datasource.url=jdbc:postgresql://localhost:5432/CRM
#spring.datasource.username=postgres
#spring.datasource.password=Srisat1$
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#jwt.secret=t5JX59LxvclJZbHFhfPfNkdC13N3Oyl+JAHeYvztHMg=
#
#spring.data.redis.host=son-yard-micromodern-82270.db.redis.io
#spring.data.redis.port=16362
#spring.data.redis.username=default
#spring.data.redis.password=ZL7TWQAzSr4uN1azgZ4QEO2QRgijqv2j
#
#app.verification-url=${VERIFICATION_URL}
#app.password-reset-url=${PASSWORD_RESET_URL}
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#
#server.port=${PORT:8080}
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true